unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -s escape-time 0
set -g history-limit 50000

# Pindah ke tab kiri/sebelumnya dengan Alt + h (tanpa prefix)
bind-key -n M-h previous-window

# Pindah ke tab kanan/berikutnya dengan Alt + l (tanpa prefix)
bind-key -n M-l next-window
